### ISSUE TITLE
`enhanced-require` not declared in package.json

### ISSUE THREAD

**Issue by unindented** [webpack-contrib/i18n-loader#1]
`enhanced-require` is being used for the _concat_ and _merge_ loaders, but it is not declared as a dependency or peer dependency in `package.json`.

**Comment by sokra** [comment]
This module is deprecated. better use the [I18nPlugin](https://github.com/webpack/i18n-webpack-plugin).

**Comment by unindented** [comment]
I got the impression the I18nPlugin only handled literal strings, not expressions. Is that not the case?

In my case I have plenty of translation keys that are generated through expressions that can only be resolved at runtime...

**Comment by briandipalma** [comment]
Why is this loader deprecated?
