### ISSUE TITLE
why is this deprecated? is there a proposed alternative? 

### ISSUE THREAD

**Issue by mattkime** [webpack-contrib/i18n-loader#3]
n/t

**Comment by SpaceK33z** [comment]
You should use https://github.com/webpack/i18n-webpack-plugin. A PR adding this info to the readme would be welcome.

**Comment by mattkime** [comment]
@SpaceK33z I was curious if I could get an explanation as to why its deprecated.

fwiw, I found it via https://webpack.js.org/loaders/i18n-loader/ - so its referenced in new(ish?) documentation.
